# Generated by Django 3.2.4 on 2021-06-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='robo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Robot', models.CharField(max_length=30)),
                ('Value', models.IntegerField()),
                ('Type', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
