# Generated by Django 3.2.4 on 2022-01-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robo',
            name='OT_call',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='robo',
            name='Position_leave',
            field=models.IntegerField(null=True),
        ),
    ]
